### ISSUE TITLE
TypeError: argument of type 'WindowsPath' is not iterable

### ISSUE THREAD

**Issue by cabfile** [ArdenButterfield/stammer#21]

**Comment by GFJHogue** [comment]
Please provide some additional context (ie. the command you're running & the entire error)

**Comment by cabfile** [comment]
```
D:\Folders\ProgrammingLanguages\Python>python stammer.py video.mp4 audio.flac re
sult.mp4
Traceback (most recent call last):
  File "stammer.py", line 270, in <module>
    main()
  File "stammer.py", line 263, in main
    process(**vars(args))
  File "stammer.py", line 156, in process
    carrier_type = file_type(carrier_path)
  File "stammer.py", line 75, in file_type
    text=True
  File "C:\Users\cabfile\AppData\Local\Programs\Python\Python37\lib\subprocess.p
y", line 488, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\cabfile\AppData\Local\Programs\Python\Python37\lib\subprocess.p
y", line 800, in __init__
    restore_signals, start_new_session)
  File "C:\Users\cabfile\AppData\Local\Programs\Python\Python37\lib\subprocess.p
y", line 1148, in _execute_child
    args = list2cmdline(args)
  File "C:\Users\cabfile\AppData\Local\Programs\Python\Python37\lib\subprocess.p
y", line 555, in list2cmdline
    needquote = (" " in arg) or ("\t" in arg) or not arg
TypeError: argument of type 'WindowsPath' is not iterable

D:\Folders\ProgrammingLanguages\Python>
```

**Comment by DouglAsshat** [comment]
Having the same issue
