### ISSUE TITLE
Do you by any chance know what I'm doing wrong here to cause this error?

### ISSUE THREAD

**Issue by Ayana225** [ArdenButterfield/stammer#24]
D:\steamer\stammer-main>python stammer.py D:\steamer\stammer-main\hams.mpeg D:\steamer\stammer-main\applevocal.wav D:\steamer\stammer-main\outputs\applehamfull.mp4
Calculating video length
Traceback (most recent call last):
  File "D:\steamer\stammer-main\stammer.py", line 291, in <module>
    main()
  File "D:\steamer\stammer-main\stammer.py", line 287, in main
    process(**vars(args))
  File "D:\steamer\stammer-main\stammer.py", line 200, in process
    carrier_framecount = float(get_framecount(carrier_path))
ValueError: could not convert string to float: '5105,\n\n'

**Comment by Ayana225** [comment]
found the issue, you can't use mpeg files
