### ISSUE TITLE
ffmpeg is unable to open a file it has created 

### ISSUE THREAD

**Issue by Just-Kamil** [ArdenButterfield/stammer#31]
this is on a larger video keep that in mind the audio and video I used for input is ~30min long 

here is the console output
`
[image2 @ 000001fa64223580] Could not open file : C:\Users\kamil\AppData\Local\Temp\tmpkvu1s3ml\frames\frame027618.png
av_interleaved_write_frame(): I/O error
Calculating video length
Separating video frames
Traceback (most recent call last):
  File "G:\odds and ends\stammer-main\stammer.py", line 285, in <module>
    main()
  File "G:\odds and ends\stammer-main\stammer.py", line 281, in main
    process(**vars(args))
  File "G:\odds and ends\stammer-main\stammer.py", line 207, in process
    subprocess.run(
  File "C:\Users\kamil\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ffmpeg', '-loglevel', 'error', '-i', WindowsPath('Visions.mp4'), WindowsPath('C:/Users/kamil/AppData/Local/Temp/tmpkvu1s3ml/frames/frame%06d.png')]' returned non-zero exit status 1.
`

I have tried this script with smaller videos and it has worked but for this larger project it ends up failing with this error

**Comment by egoughnour** [comment]
Have you checked that the frames directory is still around?
You should be able to insert
```python 
import pdb; pdb.set_trace()
```
inside `main()` in `stammer.py` right before line 207.
Then you ought to be able to check with `pathlib.Path`, which I think ought to be what is returning your `WindowsPath` instances.  Just evaluate `<variable_name>.is_file() and <variable_name>.exists()` on the Visions path and `<variable_name>.parent.resolve().is_dir() and <variable_name>.parent.resolve().exists()` on the frames path .
If `True` then there is a problem.  Otherwise the temp directory might be getting wiped out by another process.
