### ISSUE TITLE
system can't find specified file

### ISSUE THREAD

**Issue by AQ206** [ArdenButterfield/stammer#6]
Traceback (most recent call last):
  File "E:\Users\Acer2019\Desktop\\[my real name;;.;]\stammer-main\stammer.py", line 254, in <module>
    main()
  File "E:\Users\Acer2019\Desktop\\[my real name;;.;]\stammer-main\stammer.py", line 247, in main
    process(carrier_path, modulator_path, output_path)
  File "E:\Users\Acer2019\Desktop\\[my real name;;.;]\stammer-main\stammer.py", line 143, in process
    carrier_type = file_type(carrier_path)
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Users\Acer2019\Desktop\\[my real name;;.;]\stammer-main\stammer.py", line 58, in file_type
    return subprocess.run(
           ^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\subprocess.py", line 1024, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\Python311\Lib\subprocess.py", line 1493, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by GFJHogue** [comment]
This error suggests that `ffmpeg` isn't in your `Path`.

To check whether it's properly installed on Windows, on PowerShell try `Get-Command ffmpeg`
If that fails, you need to add the directory containing `ffmpeg.exe` to your `Path`.

Here's a guide: https://windowsloop.com/install-ffmpeg-windows-10/

**Comment by AQ206** [comment]
i completely skipped step 3.3 like the idiot i am 👍
