### ISSUE TITLE
error on Linux

### ISSUE THREAD

**Issue by hello10293** [ArdenButterfield/stammer#60]
I tried to use this, but it didn't work. It worked the first time, but now it's showing this:
Traceback (most recent call last):
  File "/content/stammer.py", line 309, in <module>
    main()
  File "/content/stammer.py", line 305, in main
    process(**vars(args))
  File "/content/stammer.py", line 265, in process
    build_output_video(handler, matcher)
  File "/content/stammer.py", line 157, in build_output_video
    video_handler.complete()
  File "/content/video_out.py", line 111, in complete
    subprocess.run(call,check=True)
  File "/usr/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ffmpeg', '-v', 'quiet', '-y', '-framerate', '29.931093884582257', '-stats', '-i', '/tmp/tmp82rrbr7g/outframes/frame%06d.png', '-i', '/tmp/tmp82rrbr7g/out.wav', '-c:a', 'aac', '-c:v', 'libx264', '-crf', '20', '-pix_fmt', 'yuv420p', '-shortest', '/content/outputs/srwyh.mp4']' returned non-zero exit status 1.

**Comment by hello10293** [comment]
Nevermind, I fixed it. I put the output video in a non-existent directory, which is why it displayed this error
