### ISSUE TITLE
won't work

### ISSUE THREAD

**Issue by imadeagithubaccountforthis** [ArdenButterfield/stammer#7]
log (no that is not my real name that would be a stupid real name anyways)
Traceback (most recent call last):
  File "C:\Users\snear\Desktop\videotest\stammer-main\stammer.py", line 254, in <module>
    main()
  File "C:\Users\snear\Desktop\videotest\stammer-main\stammer.py", line 247, in main
    process(carrier_path, modulator_path, output_path)
  File "C:\Users\snear\Desktop\videotest\stammer-main\stammer.py", line 143, in process
    carrier_type = file_type(carrier_path)
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\snear\Desktop\videotest\stammer-main\stammer.py", line 58, in file_type
    return subprocess.run(
           ^^^^^^^^^^^^^^^
  File "C:\Users\snear\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\snear\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1024, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\snear\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1493, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by imadeagithubaccountforthis** [comment]
wait this is already a issue reported (plus solved by actually installing ffmpeg :P)
