### ISSUE TITLE
numpy not found even though I have it

### ISSUE THREAD

**Issue by FlingYourself** [ArdenButterfield/stammer#77]
the terminal is saying no module named numpy even though I have it. Here is my terminal

C:\Users\westo> pip install numpy
Requirement already satisfied: numpy in c:\users\westo\appdata\local\programs\python\python311\lib\site-packages (1.25.2)

C:\Users\westo>python3 C:\Users\westo\Downloads\stammer-main\stammer-main\stammer.py C:\Users\westo\Downloads\tpot6.mp4 C:\Users\westo\Downloads\bfdi1a.mp4 C:\Users\westo\Downloads\outputBFDI.mp4
Traceback (most recent call last):
  File "C:\Users\westo\Downloads\stammer-main\stammer-main\stammer.py", line 5, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'

**Comment by Firepal** [comment]
You may have a separate `pip3` command to install pip packages for your `python3` installation.
Otherwise try again using `python3 -m pip install numpy`.

**Comment by PatoFlamejanteTV** [comment]
same error, but in termux.

**Comment by Firepal** [comment]
@PatoFlamejanteTV Need more info. Did you use pip to install numpy?

**Comment by Firepal** [comment]
Actually try `python3 -m pip install numpy` because that will directly tie into that particular installation of `python3` in case you unknowingly have several Python installations

**Comment by PatoFlamejanteTV** [comment]
> Actually try `python3 -m pip install numpy` because that will directly tie into that particular installation of `python3` in case you unknowingly have several Python installations

That returned me this error:

```

~ $ python3 -m pip install numpy
Collecting numpy
  Downloading numpy-2.1.0.tar.gz (18.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━ 18.9/18.9 MB 4.3 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... error
  error: subprocess-exited-with-error

  × pip subprocess to install backend dependencies did not run successfully.
  │ exit code: 1
  ╰─> [67 lines of output]
      Collecting ninja>=1.8.2
        Using cached ninja-1.11.1.1.tar.gz (132 kB)
        Installing build dependencies: started
        Installing build dependencies: finished with status 'done'
        Getting requirements to build wheel: started
        Getting requirements to build wheel: finished with status 'done'
        Preparing metadata (pyproject.toml): started
        Preparing metadata (pyproject.toml): finished with status 'done'
      Collecting patchelf>=0.11.0
        Using cached patchelf-0.17.2.1.tar.gz (167 kB)
        Installing build dependencies: started
        Installing build dependencies: finished with status 'done'
        Getting requirements to build wheel: started
        Getting requirements to build wheel: finished with status 'done'
        Preparing metadata (pyproject.toml): started
        Preparing metadata (pyproject.toml): finished with status 'done'
      Building wheels for collected packages: ninja, patchelf
        Building wheel for ninja (pyproject.toml): started
        Building wheel for ninja (pyproject.toml): finished with status 'error'
        error: subprocess-exited-with-error

        × Building wheel for ninja (pyproject.toml) did not run successfully.
        │ exit code: 1
        ╰─> [15 lines of output]
            /data/data/com.termux/files/usr/tmp/pip-build-env-a88oqh6c/overlay/lib/python3.11/site-packages/setuptools_scm/git.py:312: UserWarning: git archive did not support describe output
              warnings.warn("git archive did not support describe output")
            /data/data/com.termux/files/usr/tmp/pip-build-env-a88oqh6c/overlay/lib/python3.11/site-packages/setuptools_scm/git.py:331: UserWarning: unprocessed git archival found (no export subst applied)
              warnings.warn("unprocessed git archival found (no export subst applied)")
            Traceback (most recent call last):
              File "/data/data/com.termux/files/usr/tmp/pip-build-env-a88oqh6c/overlay/lib/python3.11/site-packages/skbuild/setuptools_wrap.py", line 643, in setup
                cmkr = cmaker.CMaker(cmake_executable)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "/data/data/com.termux/files/usr/tmp/pip-build-env-a88oqh6c/overlay/lib/python3.11/site-packages/skbuild/cmaker.py", line 145, in _init_
                self.cmake_version = get_cmake_version(self.cmake_executable)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "/data/data/com.termux/files/usr/tmp/pip-build-env-a88oqh6c/overlay/lib/python3.11/site-packages/skbuild/cmaker.py", line 102, in get_cmake_version
                raise SKBuildError(msg) from err

            Problem with the CMake installation, aborting build. CMake executable is cmake
            [end of output]

        note: This error originates from a subprocess, and is likely not a problem with pip.
        ERROR: Failed building wheel for ninja
        Building wheel for patchelf (pyproject.toml): started
        Building wheel for patchelf (pyproject.toml): finished with status 'error'
        error: subprocess-exited-with-error

        × Building wheel for patchelf (pyproject.toml) did not run successfully.
        │ exit code: 1
        ╰─> [11 lines of output]
            Traceback (most recent call last):
              File "/data/data/com.termux/files/usr/tmp/pip-build-env-0g3o6px_/overlay/lib/python3.11/site-packages/skbuild/setuptools_wrap.py", line 643, in setup
                cmkr = cmaker.CMaker(cmake_executable)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "/data/data/com.termux/files/usr/tmp/pip-build-env-0g3o6px_/overlay/lib/python3.11/site-packages/skbuild/cmaker.py", line 145, in _init_
                self.cmake_version = get_cmake_version(self.cmake_executable)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "/data/data/com.termux/files/usr/tmp/pip-build-env-0g3o6px_/overlay/lib/python3.11/site-packages/skbuild/cmaker.py", line 102, in get_cmake_version
                raise SKBuildError(msg) from err

            Problem with the CMake installation, aborting build. CMake executable is cmake
            [end of output]

        note: This error originates from a subprocess, and is likely not a problem with pip.
        ERROR: Failed building wheel for patchelf
      Failed to build ninja patchelf
      ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (ninja, patchelf)
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install backend dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
~ $
```

**Comment by PatoFlamejanteTV** [comment]
> @PatoFlamejanteTV A [cursory Google search ](https://stackoverflow.com/questions/77965881/cannot-pip-install-numpy-and-many-other-packages-in-termux-on-an-android-tabl) leads me to believe this is a quirk with termux; you have to install numpy with `pkg install python-numpy`

nvm, i just intalled pydroid3 and used :)

**Comment by PatoFlamejanteTV** [comment]
> @PatoFlamejanteTV A [cursory Google search ](https://stackoverflow.com/questions/77965881/cannot-pip-install-numpy-and-many-other-packages-in-termux-on-an-android-tabl) leads me to believe this is a quirk with termux; you have to install numpy with `pkg install python-numpy`

I tested it and it worked! I'll test it with the other dependencies now :D
