### ISSUE TITLE
how can i fix this?

### ISSUE THREAD

**Issue by zarbensr91** [ArdenButterfield/stammer#8]
C:\Users\*myname*\Downloads\stammer-main\stammer-main>python stammer.py ‪C:\Users\*myname*\Videos\return_of_the_kipz360P.mp4 ‪C:\Users\*myname*\Music\BGMs\badapel.mp3 C:\Users\*myname*\Downloads\stammer-main\stammer-main\outputs\cccc.mp4
Traceback (most recent call last):
  File "C:\Users\*myname*\Downloads\stammer-main\stammer-main\stammer.py", line 254, in <module>
    main()
  File "C:\Users\*myname*\Downloads\stammer-main\stammer-main\stammer.py", line 247, in main
    process(carrier_path, modulator_path, output_path)
  File "C:\Users\*myname*\Downloads\stammer-main\stammer-main\stammer.py", line 143, in process
    carrier_type = file_type(carrier_path)
  File "C:\Users\*myname*\Downloads\stammer-main\stammer-main\stammer.py", line 58, in file_type
    return subprocess.run(
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ffprobe', '-loglevel', 'error', '-show_entries', 'stream=codec_type', '-of', 'csv=p=0', WindowsPath('\u202aC:/Users/myname/Videos/return_of_the_kipz360P.mp4')]' returned non-zero exit status 1.

**Comment by GFJHogue** [comment]
> `WindowsPath('\u202aC:/Users/myname/Videos/return_of_the_kipz360P.mp4')`

It looks like there's an invisible character `U+202A` at the start of this file-path (somehow included from a copy-paste?)

I would try retyping the path to ensure there aren't any extra characters.
