### ISSUE TITLE
OverflowError: cannot fit 'int' into an index-sized integer

### ISSUE THREAD

**Issue by dinorokii** [ArdenButterfield/stammer#86]
I have received this error and I haven't seen it in Issues yet

```
raceback (most recent call last):
  File "C:\Users\Dinoroki\AppData\Local\Programs\Python\Python39-32\lib\site-packages\scipy\io\wavfile.py", line 462, in _read_data_chunk
    data = numpy.fromfile(fid, dtype=dtype, count=count)
io.UnsupportedOperation: fileno

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Dinoroki\stammer-main\stammer.py", line 307, in <module>
    main()
  File "C:\Users\Dinoroki\stammer-main\stammer.py", line 303, in main
    process(**vars(args))
  File "C:\Users\Dinoroki\stammer-main\stammer.py", line 240, in process
    _, carrier_audio = wavfile.read(get_audio_as_wav_bytes(carrier_path))
  File "C:\Users\Dinoroki\AppData\Local\Programs\Python\Python39-32\lib\site-packages\scipy\io\wavfile.py", line 689, in read
    data = _read_data_chunk(fid, format_tag, channels, bit_depth,
  File "C:\Users\Dinoroki\AppData\Local\Programs\Python\Python39-32\lib\site-packages\scipy\io\wavfile.py", line 465, in _read_data_chunk
    data = numpy.frombuffer(fid.read(size), dtype=dtype)
OverflowError: cannot fit 'int' into an index-sized integer
```

i don't know if this is painfully obvious why it isn't working or something

**Comment by Firepal** [comment]
What's your Python version? 3.10+ is required

**Comment by dinorokii** [comment]
turns out i was using 3.9, upgrading to 3.13 worked. thank you!
