### ISSUE TITLE
Didn't work on Linux

### ISSUE THREAD

**Issue by andresbravo2003** [ArdenButterfield/stammer#87]
I'm a Arch Linux User, and I'm just trying to execute to get better results, but all I have is this error:

Traceback (most recent call last):
  File "/home/andres-arch/Downloads/stammer-main/stammer.py", line 307, in <module>
    main()
  File "/home/andres-arch/Downloads/stammer-main/stammer.py", line 303, in main
    process(**vars(args))
  File "/home/andres-arch/Downloads/stammer-main/stammer.py", line 222, in process
    subprocess.run(call,check=True)
  File "/usr/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ffmpeg', '-v', 'quiet', '-stats', '-i', 'kim.mp4', '/tmp/tmpx0j2xoz5/frames/frame%06d.png']' returned non-zero exit status 228.

is there any solution?

**Comment by andresbravo2003** [comment]
Update: Oh right, just shortened the file by not running out of space because of the frames. oops. hopefully another solution will need help.
