### ISSUE TITLE
broken pipe and temp files being used by another process

### ISSUE THREAD

**Issue by CamtheKirby** [ArdenButterfield/stammer#90]
I don't know if anyone is active on this but it gives me this error: 

Calculating video length
Separating video frames
frame=10120 fps=267 q=-0.0 Lsize=N/A time=00:07:01.66 bitrate=N/A speed=11.1x
reading audio
analyzing audio
creating output audio
building output video
Traceback (most recent call last):
  File "C:\Users\among\OneDrive\Desktop\python\stammer\stammer.py", line 303, in main
    process(**vars(args))
  File "C:\Users\among\OneDrive\Desktop\python\stammer\stammer.py", line 263, in process
    build_output_video(handler, matcher)
  File "C:\Users\among\OneDrive\Desktop\python\stammer\stammer.py", line 144, in build_output_video
    video_handler.write_frame(video_frame_i,video_handler.get_frame(carrier_video_frame))
  File "C:\Users\among\OneDrive\Desktop\python\stammer\video_out.py", line 127, in write_frame
    self.out_proc.stdin.write(frame.read())
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\shutil.py", line 632, in _rmtree_unsafe
    os.unlink(fullname)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\among\\AppData\\Local\\Temp\\tmpfffduw1v\\frames\\frame005916.png'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\among\OneDrive\Desktop\python\stammer\stammer.py", line 307, in <module>
    main()
  File "C:\Users\among\OneDrive\Desktop\python\stammer\stammer.py", line 300, in main
    with tempfile.TemporaryDirectory() as tempdir:
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\tempfile.py", line 943, in __exit__
    self.cleanup()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\tempfile.py", line 947, in cleanup
    self._rmtree(self.name, ignore_errors=self._ignore_cleanup_errors)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\tempfile.py", line 929, in _rmtree
    _shutil.rmtree(name, onerror=onerror)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\shutil.py", line 787, in rmtree
    return _rmtree_unsafe(path, onerror)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\shutil.py", line 629, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\shutil.py", line 634, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\tempfile.py", line 893, in onerror
    _os.unlink(path)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\among\\AppData\\Local\\Temp\\tmpfffduw1v\\frames\\frame005916.png'

I downloaded the requirements ffmpeg and I think I have a Python version that should work with it (3.11.9)

It worked the first time so I don't know what's causing it to have and broken pipe

**Comment by CamtheKirby** [comment]
I found out how to fix it just delete the folder in %temp% that is used for it (or just delete every file that isn't needed in the %temp% folder) and it should work
