### ISSUE TITLE
ValueError: could not convert string to float: '4491,\n' [Termux]

### ISSUE THREAD

**Issue by PatoFlamejanteTV** [ArdenButterfield/stammer#92]
Hi, I was using Stammer, when suddenly it gave this error:

```
~/stammer $ python stammer.py Record_2024-10-28-21-55-54.mp4 creepbell.mp3 finaaaaaal.mp4
Calculating video length
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/stammer/stammer.py", line 307, in <module>
    main()
  File "/data/data/com.termux/files/home/stammer/stammer.py", line 303, in main
    process(**vars(args))
  File "/data/data/com.termux/files/home/stammer/stammer.py", line 201, in process
    carrier_framecount = float(get_framecount(carrier_path))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: could not convert string to float: '4491,\n'
~/stammer $
```

![Screenshot_2024-10-28-22-02-58-75_84d3000e3f4017145260f7618db1d683.jpg](https://github.com/user-attachments/assets/c511a4be-0708-478b-8d07-ba9830e3de75)

This is the first time it has done this, it has never happened either when I used it on Windows or the other uses on Termux.

**Comment by Linuxman12** [comment]
i got more errors :(
